services:
  vault:
    build:
      dockerfile: ./docker/src/vault/Dockerfile
      args:
        VAULT_ADDR: ${VAULT_ADDR}
    container_name: vault
    ports:
      - "8200:8200"
    env_file:
      - .env
    volumes:
      - vault_data:/vault/data
      - shared-volume:/shared-volume
    networks:
      - backend_network

  nginx:
    build:
      dockerfile: ./docker/src/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web
    networks:
      - backend_network

  redis:
    container_name: redis
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - backend_network

  web:
    container_name: web
    build:
      dockerfile: ./docker/src/django/Dockerfile
    # ports:
    #   - "6379:6379"
    volumes:
      - ./main:/app/main
      - shared-volume:/shared-volume
    environment:
      - DEBUG=${WEB_DEBUG}
    depends_on:
      - vault
      - db
      - redis
    networks:
      - backend_network
      
  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend_network
      
volumes:
  postgres_data:
  vault_data:
  shared-volume:
    driver: local

networks:
  backend_network:
    driver: bridge