services:
  nginx:
    build:
      context: ..
      dockerfile: ./docker/src/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web
    networks:
      - backend_network

  vault:
    build:
      context: ..
      dockerfile: ./docker/src/vault/Dockerfile
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
      - vault_data:/vault/data
    networks:
      - backend_network

  redis:
    container_name: redis
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - backend_network

  web:
    container_name: web
    build:
      context: ..
      dockerfile: ./docker/src/django/Dockerfile
    # ports:
    #   - "6379:6379"
    volumes:
      - ./../main:/app/main
      # - ./main/staticfiles:/app/main/staticfiles
    environment:
      - DEBUG=True
    depends_on:
      - db
      - redis
    networks:
      - backend_network
      
  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ft_user
      POSTGRES_PASSWORD: ft_password
      POSTGRES_DB: ft_transcendence
    ports:
      - "5432:5432"
    networks:
      - backend_network
      
volumes:
  postgres_data:
  vault_data:

networks:
  backend_network:
    driver: bridge