from django.urls import path

from . import views

urlpatterns = [
    path("is_auth/", views.is_auth, name="is_auth"),
	path("get_username/", views.get_username, name="get_username"),
	path("update_password/", views.update_password, name="update_password"),
	path("update_username/", views.update_username, name="update_username"),
	path("get_avatar/", views.get_avatar, name="get_avatar"),
	path("upload_avatar/", views.upload_avatar, name="upload_avatar"),
	path("user_is_online/", views.user_is_online, name="user_is_online"),
	path("acceptFriendsRequest/", views.acceptFriendsRequest, name="acceptFriendsRequest"),
	path("denyFriendsRequest/", views.denyFriendsRequest, name="denyFriendsRequest"),
	path("removeFriends/", views.removeFriends, name="removeFriends"),
	path("getFriendsList/", views.getFriendsList, name="getFriendsList"),
	path("getRequestFriendsList/", views.getRequestFriendsList, name="getRequestFriendsList"),
	path("user_exist/", views.user_exist, name="user_exist"),
	path("user_not_friend_exist/", views.user_not_friend_exist, name="user_not_friend_exist"),
	path("sendRequestFriends/", views.sendRequestFriends, name="sendRequestFriends"),
	path("user_is_42/", views.user_is_42, name="user_is_42"),
	path("getUserLang/", views.getUserLang, name="getUserLang"),
	path("setUserLang/", views.setUserLang, name="setUserLang"),
	path("get_rank/", views.get_rank, name="get_rank"),
	path("get_win/", views.get_win, name="get_win"),
	path("get_lose/", views.get_lose, name="get_lose"),
	path("get_Nmatches/", views.get_Nmatches, name="get_Nmatches"),
	path("get_win_rate/", views.get_win_rate, name="get_win_rate"),
	path("add_win/", views.add_win, name="add_win"),
	path("add_lose/", views.add_lose, name="add_lose"),
	path("update_win_rate/", views.update_win_rate, name="update_win_rate"),
	path("create_match/", views.create_match, name="create_match"),
	path("get_Lastmatches/", views.get_Lastmatches, name="get_Lastmatches"),
	path("get_LastGames/", views.get_LastGames, name="get_LastGames"),
	path("update_rank/", views.update_rank, name="update_rank"),
	path("update_rank_brick/", views.update_rank_brick, name="update_rank_brick"),
	path("get_NumberOne/", views.get_NumberOne, name="get_NumberOne"),
	path("get_thethree/", views.get_thethree, name="get_thethree"),
	path("get_NumberOneBrick/", views.get_NumberOneBrick, name="get_NumberOneBrick"),
	path("get_thethreeBrick/", views.get_thethreeBrick, name="get_thethreeBrick"),
	path("create_party/", views.create_party, name="create_party"),
	path("get_myStat/", views.get_myStat, name="get_myStat"),
	path("get_myBrickStat/", views.get_myBrickStat, name="get_myBrickStat"),
]